### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by enoriega** [ml4ai/ASKEM-TA1-DataModel#22]
The current state of the code requires python >= 3.9. To bundle this up with the SKEMA services, we need to make it work  on python 3.8

**Comment by adarshp** [comment]
What's the timeline for this? It may not be necessary, depending on when the PA folks can update the pipeline to use tree-sitter, thus releasing us from being locked to Python 3.8

**Comment by enoriega** [comment]
I planed to do it today.  It certainly it has to be done before the hackaton.

**Comment by myedibleenso** [comment]
I believe this is complete.  @enoriega ?
