### ISSUE TITLE
import_arizona() does not work on the latest Arizona extraction standardized_extractions_documents_5Feb1-s2.0-S2211379721005490-main--COSMOS-data.json

### ISSUE THREAD

**Issue by Tranway1** [ml4ai/ASKEM-TA1-DataModel#9]
I paste the head sample of the latest Arizona extraction (format A) for 1-s2.0-S2211379721005490-main. This is totally different from the format of extraction [sample](https://github.com/ml4ai/ASKEM-TA1-DataModel/blob/main/examples/arizona_output_example.json) (format B). I was wondering how to convert from A to B?
`{
	"variable_statements": [
		{
			"id": "R:-1804348017",
			"variable": {
				"name": "LV",
				"metadata": [],
				"dkg_groundings": [],
				"column": [],
				"paper": {
					"id": "1-s2.0-S2211379721005490-main.pdf",
					"file_directory": "1-s2.0-S2211379721005490-main.pdf",
					"doi": ""
				},
				"equations": []
			},
			"value": {
				"value": "LotkaVolterra",
				"type": "description",
				"dkg_grounding": null
			},
			"metadata": [
				{
					"type": "text_span",
					"value": "LotkaVolterra (LV"
				},
				{
					"type": "cosmos_location",
					"value": "1,11,2185,2202"
				},
				{
					"type": "scenario_location",
					"value": "V. Volterra"
				},
				{
					"type": "scenario_location",
					"value": "Lotka-Volterra"
				}
			],
			"provenance": {
				"method": "SKEMA",
				"description": "SKEMA text reading pipeline v0.5"
			}
		},`

**Comment by enoriega** [comment]
@Tranway1 and I met and discussed this issue. The format in the example above is the output, not the input
